#openssl genrsa -out keypair.pem 2048
#openssl rsa -in keypair.pem -pubout -out public.pem
#openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in keypair.pem -out private.pem

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql